### ISSUE TITLE
2.1.8 randomly fails

### ISSUE THREAD

**Issue by royharoush** [gigarepo/addons#2]
Hi, 
This is a long shot, since im using kodi 18 (for the exodus redux support), but let's try. 
I'm using 2.1.8. for the most parts after rebooting my streamer the first subtitle from the first stream works, but afterwards they all fail. 
Tried to dig into the logs but couldn't find any reason for that. 
Tried uninstall and reinstalled and the whole reboot stuff :|
any chance you can give me a hint on how to solve this issue or if you need any specific log file to ? 
Thanks !

**Comment by gigarepo** [comment]
Fixed.
